name: Spring Boot CI

on:
  push:
      branches: ["master"]
  pull_request:
      branches: ["master"]

jobs:
    build:
      runs-on: windows latest
       steps:
       - name: Checkout source
         uses: action/checkout@v3

       - name: Set up JDK 23
         uses: action/setup-java@v3
         with:
            java-version: "23"
            distribution: "temurin"
